baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Druidic Synthesis'
theme = 'druid'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true
  themeVariant = ['relearn-light', 'relearn-dark']
  disableSearch = true